base: # Not a config - only base value
  active_strategy: 'first'

  nav:
    attr:
      class: 'nav nav-tabs'

  nav_item:
    icon: ''
    label: ''
    active: false
    url: null
    route: null
    route_params: [ ]
    attr:
      class: 'nav-item'
    attr_link:
      class: 'nav-link'

default:
  nav:
    attr:
      class: 'nav nav-tabs mb-3'

default_justified:
  nav:
    attr:
      class: 'nav nav-tabs nav-justified mb-3'

pills:
  nav:
    attr:
      class: 'nav nav-pills bg-nav-pills mb-3'
  nav_item:
    attr_link:
      class: 'nav-link rounded-0'

pills_justified:
  nav:
    attr:
      class: 'nav nav-pills bg-nav-pills nav-justified mb-3'
  nav_item:
    attr_link:
      class: 'nav-link rounded-0'

bordered:
  nav:
    attr:
      class: 'nav nav-tabs nav-bordered mb-3'

bordered_justified:
  nav:
    attr:
      class: 'nav nav-tabs nav-bordered nav-justified mb-3'